### ISSUE TITLE
增加功能：引用展开

### ISSUE THREAD

**Issue by yudanhezhongweijie** [zwt-ss/DawnIsland#4]

**Comment by MisoraRin** [comment]
1. 需要提供串内展开（参照芦苇岛）和弹出对话框（参照蓝岛）两种方式以供用户选择。当前选择一种实现即可。
2. 有两个接口可以解析引用，使用fastmirror更快但不支持跳转原串。
3. 串内展开需要使用三个Span分别控制引用线、文字背景、字体大小。

**Comment by yudanhezhongweijie** [comment]
串内展开比较难实现是因为目前的layout只是一个普通的textview，而引用可能会出现图片加文字的形式，图片还需要加大图模式，所以先暂时采用弹出dialog的形式。

**Comment by yudanhezhongweijie** [comment]
因为content是在model直接改成了一个string，目前不能弹出dialog，只能显示引用的文字。这是因为seriescontentmodel有一些设计上的问题。身为一个model，他不仅读取了数据，而且还改成了view接受的形式。修改可能需要整个页面架构上调整

**Comment by yudanhezhongweijie** [comment]
考虑到要添加监听，比较好的办法是增加一个新的textview或者layout。在没有引用的时候隐藏，有的时候就排版
